// Source: hiarng_unit_abbreviations.csv. CSMS2 corrected from the source's
// "Shop 1" typo to "Shop 2". Abbreviations are seeded/compared UPPERCASE.
export const UNIT_SEED: { abbreviation: string; fullName: string }[] = [
  { abbreviation: "103TC", fullName: "103 TRP CMD" },
  { abbreviation: "DCSIM", fullName: "DCSIM" },
  { abbreviation: "111AB", fullName: "111 ARMY BAND" },
  { abbreviation: "DOMS", fullName: "Directorate of Military Support (J3)" },
  { abbreviation: "126AV", fullName: "126TH AVN CO" },
  { abbreviation: "ENV", fullName: "Environmental" },
  { abbreviation: "140AV", fullName: "140 AVN Rgmt" },
  { abbreviation: "EOC", fullName: "Emergency Operations Center" },
  { abbreviation: "183AV", fullName: "183 AVN Rgmt" },
  { abbreviation: "ESGR", fullName: "Employer Support of Guard and Reserve" },
  { abbreviation: "189AV", fullName: "189 AVN Rgmt" },
  { abbreviation: "FMO", fullName: "Facility Maintenance Office" },
  { abbreviation: "207AV", fullName: "207 AVN Rgmt" },
  { abbreviation: "1950", fullName: "1950 Commercial Contracting Team" },
  { abbreviation: "FMS1", fullName: "Field Maint Shop 1 (Kalaeloa)" },
  { abbreviation: "FMS2", fullName: "Field Maint Shop 2 (Wahiawa)" },
  { abbreviation: "211AV", fullName: "211 AVN Rgmt" },
  { abbreviation: "FMS3", fullName: "Field Maint Shop 3 (Maui)" },
  { abbreviation: "230EN", fullName: "230 EN Co" },
  { abbreviation: "FMS5", fullName: "Field Maint Shop 5 (Kauai)" },
  { abbreviation: "297EN", fullName: "297 EN Det" },
  { abbreviation: "G1", fullName: "G1" },
  { abbreviation: "298RT", fullName: "298 Regmt" },
  { abbreviation: "G2", fullName: "G2" },
  { abbreviation: "299A", fullName: "299CAV TRP A" },
  { abbreviation: "G3", fullName: "G3" },
  { abbreviation: "299B", fullName: "299CAV TRP B" },
  { abbreviation: "G4", fullName: "G4" },
  { abbreviation: "299C", fullName: "299CAV TRP C" },
  { abbreviation: "MFH", fullName: "Military Funeral Honors" },
  { abbreviation: "299D", fullName: "299CAV D Co (DFSC)" },
  { abbreviation: "HRO", fullName: "HRO" },
  { abbreviation: "299H", fullName: "299CAV HQ" },
  { abbreviation: "JFHHD", fullName: "JFHQ HHD" },
  { abbreviation: "29BCT", fullName: "29th IBCT" },
  { abbreviation: "MED", fullName: "Medical Dettachment" },
  { abbreviation: "445AV", fullName: "445 AVN SPT BN" },
  { abbreviation: "MPAD", fullName: "117 Mobile Public Affairs Det" },
  { abbreviation: "487A", fullName: "487FA BATTERY A" },
  { abbreviation: "PAO", fullName: "Public Affairs Office" },
  { abbreviation: "487B", fullName: "487FA BATTERY B" },
  { abbreviation: "PBO", fullName: "Property Book Office" },
  { abbreviation: "487F", fullName: "487FA Co F (FFSC)" },
  { abbreviation: "PUBS", fullName: "Publications" },
  { abbreviation: "487H", fullName: "487FA HQ" },
  { abbreviation: "RAID", fullName: "Recon and Interdiction Det" },
  { abbreviation: "641AV", fullName: "641 AVN Rgmt" },
  { abbreviation: "RRB", fullName: "Recruiting and Retention Battalion" },
  { abbreviation: "93CST", fullName: "93 CST" },
  { abbreviation: "RTSM", fullName: "Regional Training Site Maint" },
  { abbreviation: "SAFE", fullName: "Safety Office" },
  { abbreviation: "SFP", fullName: "State Family Program" },
  { abbreviation: "USPFO", fullName: "USPFO" },
  { abbreviation: "UTES", fullName: "UTES" },
  { abbreviation: "AASF1", fullName: "Army Aviation Support Facility 1" },
  { abbreviation: "AASF2", fullName: "Army Aviation Support Facility 2" },
  { abbreviation: "BSBA", fullName: "Brigade Support Battalion Co A" },
  { abbreviation: "BSBB", fullName: "Brigade Support Battalion Co B" },
  { abbreviation: "BSBC", fullName: "Brigade Support Battalion Co C" },
  { abbreviation: "BSBH", fullName: "Brigade Support Battalion HQ" },
  { abbreviation: "BEBA", fullName: "Brigade Engineer Battalion Co A (EN)" },
  { abbreviation: "BEBB", fullName: "Brigade Engineer Battalion Co B (EN)" },
  { abbreviation: "BEBC", fullName: "Brigade Engineer Battalion Co C (SIGNAL)" },
  { abbreviation: "BEBD", fullName: "Brigade Engineer Battalion Co D (MI)" },
  { abbreviation: "BEBE", fullName: "Brigade Engineer Battalion Co E (EFSC)" },
  { abbreviation: "BEBH", fullName: "Brigade Engineer Battalion HQ" },
  { abbreviation: "CD", fullName: "Counter Drug" },
  { abbreviation: "CERFP", fullName: "CERFP" },
  { abbreviation: "COFS", fullName: "Chief of Staff Office" },
  { abbreviation: "CSMS1", fullName: "Combined Support Maint Shop 1" },
  { abbreviation: "CSMS2", fullName: "Combined Support Maint Shop 2" },
];
