"use client";
import { useActionState, useState } from "react";
import { updateItemDetailsAction } from "@/app/actions/items";
import { SuggestCombobox } from "@/components/SuggestCombobox";
import type { ItemFieldSuggestions } from "@/modules/items/items.service";

export type ItemDetailsValues = {
  id: string;
  deviceName: string | null;
  /** The autogenerated name MDM wants, when the import refused to apply it.
   *  Non-null means this device needs renaming in Intune. Read-only: it is the
   *  importer's note, so it is deliberately absent from the edit form. */
  mdmProposedName: string | null;
  /** The last real name an autogenerated one replaced, from edit history. This
   *  is what to rename the device back to in Intune. */
  previousRealName: string | null;
  /** Autogenerated names MDM has proposed and since moved on from, newest
   *  first. Empty until MDM re-enrols the same device twice. */
  supersededProposals: string[];
  homeUnit: string | null;
  deviceUIC: string | null;
  deviceCategory: string | null;
  storageLocation: string | null;
  currentUserEmail: string | null;
  currentPosition: string | null;
  notes: string | null;
  lastLogonUserPrincipalName: string | null;
  lastLogonDate: string | null;
  enrollmentDate: string | null;
  compliance: string | null;
  lastSyncDateTime: string | null;
};

type Props = {
  item: ItemDetailsValues;
  isAdmin: boolean;
  units: { abbreviation: string; fullName: string }[];
  // The MANAGED device-category vocabulary, for the picker below. Suggestions
  // only — Item.deviceCategory stays free text on purpose.
  categories: string[];
  // The free-text catalogue vocabularies (make/model/UIC), for the same
  // suggestion mechanism. Admin-only, like `units` and `categories` above.
  suggestions: ItemFieldSuggestions;
  // Pre-formatted on the server so this component stays free of date/party logic.
  dateLogged: string;
  loggedBy: string;
  handReceiptHolder: string;
  lastEdited: string | null;
};

const dash = <span className="subtle">—</span>;

export function ItemDetailsCard({ item, isAdmin, units, categories, suggestions, dateLogged, loggedBy, handReceiptHolder, lastEdited }: Props) {
  const [editing, setEditing] = useState(false);
  const [state, action, pending] = useActionState(updateItemDetailsAction, undefined);

  // Leave edit mode once a save succeeds; the server re-renders with new values.
  // "Storing information from previous renders" pattern (see
  // https://react.dev/reference/react/useState#storing-information-from-previous-renders):
  // compared on `state` IDENTITY, not a derived boolean, and only written when it
  // changes from the previous render — never unconditionally — so this is a
  // guarded render-time write, not the unconditional kind react-hooks/set-state-in-render
  // flags. useActionState returns the SAME object across re-renders until a new
  // submit resolves, so every successful submit yields a fresh object (closing the
  // editor, even on a second save), while merely re-opening the editor via the
  // Edit button leaves `state` unchanged (so it stays open). A boolean dep, or an
  // unconditional write, would leave `ok` true forever and slam the form shut every
  // time Edit was clicked again — do not "simplify" this into either.
  const [prevState, setPrevState] = useState(state);
  if (state !== prevState) {
    setPrevState(state);
    if (state && "ok" in state && state.ok) setEditing(false);
  }

  return (
    <div className="card">
      <div className="row">
        <div className="card__title">Item details</div>
        <span className="spacer" />
        {!editing && (
          <button type="button" className="btn btn-secondary btn-sm" onClick={() => setEditing(true)}>
            Edit
          </button>
        )}
      </div>

      {editing ? (
        <form action={action} className="stack-sm">
          <input type="hidden" name="id" value={item.id} />
          <div className="form-grid">
            {/* deviceName, homeUnit, deviceUIC, deviceCategory and notes are
                ADMIN-only. A standard USER edits only the current holder email
                and position, so these inputs are not rendered for them — and
                updateItemDetailsAction re-enforces this server-side by picking
                userItemDetailsSchema, which strips them. */}
            {isAdmin && (
              <>
                <div className="field">
                  <label className="label" htmlFor="ed-deviceName">Device Name<span className="req"> *</span></label>
                  <input id="ed-deviceName" className="input" name="deviceName" defaultValue={item.deviceName ?? ""} required />
                </div>
                <div className="field">
                  <label className="label" htmlFor="ed-homeUnit">Home unit</label>
                  <SuggestCombobox
                    id="ed-homeUnit"
                    name="homeUnit"
                    options={units.map((u) => u.fullName)}
                    placeholder="Search units…"
                    defaultValue={item.homeUnit ?? ""}
                  />
                </div>
                <div className="field">
                  <label className="label" htmlFor="ed-deviceUIC">Unit (UIC)</label>
                  <SuggestCombobox
                    id="ed-deviceUIC"
                    name="deviceUIC"
                    options={suggestions.deviceUIC}
                    defaultValue={item.deviceUIC ?? ""}
                  />
                </div>
                <div className="field">
                  <label className="label" htmlFor="ed-deviceCategory">Category</label>
                  {/* Free text with the managed vocabulary as SUGGESTIONS, never
                      a locked <select> — an unregistered category must stay
                      typeable (it is learned into the list on save). */}
                  <SuggestCombobox
                    id="ed-deviceCategory"
                    name="deviceCategory"
                    options={categories}
                    placeholder="e.g. Laptop"
                    defaultValue={item.deviceCategory ?? ""}
                  />
                </div>
                <div className="field">
                  <label className="label" htmlFor="ed-storageLocation">Storage location (SLoc)</label>
                  <SuggestCombobox
                    id="ed-storageLocation"
                    name="storageLocation"
                    options={suggestions.storageLocation}
                    placeholder="e.g. Bldg 400 Cage 3"
                    defaultValue={item.storageLocation ?? ""}
                  />
                </div>
              </>
            )}
            <div className="field">
              <label className="label" htmlFor="ed-currentUserEmail">Current user email</label>
              {/* inputMode, NOT type="email" — CSV-imported rows hold names like
                  "SGT Smith" in this column (import.ts copies `assignedUser`
                  verbatim), and a browser-side email constraint would block
                  saving the OTHER fields on this form. The server schema does
                  not validate an address either. */}
              <input id="ed-currentUserEmail" className="input" inputMode="email" name="currentUserEmail" defaultValue={item.currentUserEmail ?? ""} placeholder="e.g. jane.doe@unit.mil" />
            </div>
            <div className="field">
              <label className="label" htmlFor="ed-currentPosition">Current position</label>
              <input id="ed-currentPosition" className="input" name="currentPosition" defaultValue={item.currentPosition ?? ""} placeholder="e.g. Supply Sergeant" />
            </div>
            {isAdmin && (
              <div className="field col-span-2">
                <label className="label" htmlFor="ed-notes">Notes</label>
                <textarea id="ed-notes" className="textarea" name="notes" defaultValue={item.notes ?? ""} />
              </div>
            )}
          </div>
          {state && "error" in state && state.error && <p role="alert" className="alert-error">{state.error}</p>}
          <div className="row">
            <button type="submit" className="btn btn-primary" disabled={pending}>
              {pending ? "Saving…" : "Save changes"}
            </button>
            <button type="button" className="btn btn-ghost" onClick={() => setEditing(false)} disabled={pending}>
              Cancel
            </button>
          </div>
        </form>
      ) : (
        <dl className="dl">
          <dt>Device Name</dt>
          <dd>
            {item.deviceName || dash}
            {/* Rendered beside the name it is about, rather than as a row of
                its own further down, because the whole message is "this name
                and MDM's disagree". */}
            {item.mdmProposedName && (
              <p className="alert-warning" style={{ marginTop: 6 }}>
                MDM calls this device <strong>{item.mdmProposedName}</strong> — an
                autogenerated name from a re-enrolment. The import kept the name
                above instead of overwriting it. Rename the device in Intune and
                this note clears itself on the next import.
              </p>
            )}
            {/* Behind a disclosure, not always on: this answers a question only
                someone actively fixing a badly-named device asks, and the two
                facts come from edit history rather than the item row — a column
                overwritten in place remembers nothing.

                `<details>` + a `.btn` summary is the documented pattern here:
                preflight is absent, so `<summary>` keeps `display: list-item`
                and its triangle, and `.btn`'s `inline-flex` is what removes it.
                Native, so it works before hydration and takes Enter/Space for
                free. */}
            {(item.previousRealName || item.supersededProposals.length > 0) && (
              <details className="stack-sm" style={{ marginTop: 6 }}>
                <summary className="btn btn-ghost btn-sm">Previous names</summary>
                <dl className="dl" style={{ marginTop: 6 }}>
                  {item.previousRealName && (
                    <>
                      <dt>Before it was renamed</dt>
                      <dd>
                        <strong>{item.previousRealName}</strong>
                        <span className="subtle"> — rename it back to this in Intune.</span>
                      </dd>
                    </>
                  )}
                  {item.supersededProposals.length > 0 && (
                    <>
                      <dt>MDM previously wanted</dt>
                      {/* Superseded proposals, newest first. Their value is that
                          a long list means this device has been re-enrolled
                          repeatedly and nobody has renamed it. */}
                      <dd>{item.supersededProposals.join(", ")}</dd>
                    </>
                  )}
                </dl>
              </details>
            )}
          </dd>
          <dt>Home unit</dt>
          <dd>{item.homeUnit || dash}</dd>
          <dt>Device UIC</dt>
          <dd>{item.deviceUIC || dash}</dd>
          <dt>Category</dt>
          <dd>{item.deviceCategory || dash}</dd>
          <dt>Storage location</dt>
          <dd>{item.storageLocation || dash}</dd>
          <dt>Current user email</dt>
          <dd>{item.currentUserEmail || dash}</dd>
          <dt>Current position</dt>
          <dd>{item.currentPosition || dash}</dd>
          <dt>Last logon user</dt>
          <dd>{item.lastLogonUserPrincipalName || dash}</dd>
          <dt>Last logon date</dt>
          <dd>{item.lastLogonDate || dash}</dd>
          {/* When MDM last checked in, as opposed to when a person last signed
              in. Sits next to the logon date because the pair is what says
              whether a device is alive-but-unused or simply gone. */}
          <dt>Last sync date</dt>
          <dd>{item.lastSyncDateTime || dash}</dd>
          <dt>Enrollment date</dt>
          <dd>{item.enrollmentDate || dash}</dd>
          <dt>Compliance</dt>
          <dd>{item.compliance || dash}</dd>
          {isAdmin && (
            <>
              <dt>Notes</dt>
              <dd>{item.notes || dash}</dd>
            </>
          )}
          <dt>Date logged</dt>
          <dd>{dateLogged}</dd>
          <dt>Logged by</dt>
          <dd>{loggedBy}</dd>
          <dt>Hand-receipt holder</dt>
          <dd>{handReceiptHolder}</dd>
          {lastEdited && (
            <>
              <dt>Last edited</dt>
              <dd className="subtle">{lastEdited}</dd>
            </>
          )}
        </dl>
      )}
    </div>
  );
}
