import { importRowSchema } from "./items.schema";
import type { RawRow } from "./csv";
import { diffItemFields, type FieldChange, type ItemLoggedFields } from "./item-diff";
import { parseLastLogonAt } from "./readiness";

export type SkippedRow = { row: number; serialNumber: string; reason: string };

/**
 * An MDM-autogenerated device name, as produced by a re-enrolment: `BE-`
 * followed by exactly 12 uppercase alphanumerics.
 *
 * Measured against the live fleet export (2026-08-11): **91 of 1071 device
 * names carried this shape and every single one matched it exactly** — there
 * was no `BE-` name of any other form — while every other device used the
 * organisation's own `NGHI*` convention. So the pattern separates the two
 * cleanly, with no false positives to worry about.
 *
 * Deliberately anchored and case-SENSITIVE. A looser rule (`startsWith("BE-")`)
 * would swallow a real name that happened to begin with those characters, and
 * wrongly refusing to apply a genuine rename is the worse failure: the flag it
 * raises asks a human to go and change something in Intune that is already
 * correct.
 */
export function isAutogeneratedDeviceName(name: string | null | undefined): boolean {
  return typeof name === "string" && /^BE-[A-Z0-9]{12}$/.test(name);
}

// The columns of an existing item needed to match a CSV row and diff it. Fetched
// in one findMany by the caller and keyed by lowercased serial (citext identity).
export type ExistingItem = {
  id: string;
  // "ACTIVE" | "RETIRED". Retired items still update, but we never write an
  // ItemEdit history row for them (an MDM refresh shouldn't add churn to the
  // audit trail of an out-of-service device).
  status: string;
  make: string;
  model: string;
  deviceName: string | null;
  homeUnit: string | null;
  deviceUIC: string | null;
  deviceCategory: string | null;
  storageLocation: string | null;
  currentUserEmail: string | null;
  lastLogonUserPrincipalName: string | null;
  lastLogonDate: string | null;
  enrollmentDate: string | null;
  compliance: string | null;
  lastSyncDateTime: string | null;
  /** The autogenerated name a previous import refused to apply, or null. Read
   *  so the flag can be CLEARED once MDM stops disagreeing — without it, a
   *  device renamed properly in Intune would sit on the worklist for ever. */
  mdmProposedName: string | null;
};

// A row that will create a new item. make/model are required for creates (checked
// below); the rest are set only when the CSV provided a value.
export type NewItemImport = {
  make: string;
  model: string;
  serialNumber: string;
  deviceName?: string;
  homeUnit?: string;
  deviceUIC?: string;
  deviceCategory?: string;
  storageLocation?: string;
  notes?: string;
  currentUserEmail?: string;
  lastLogonUserPrincipalName?: string;
  lastLogonDate?: string;
  /** Derived from lastLogonDate at plan time; see readiness.ts. */
  lastLogonAt?: Date;
  enrollmentDate?: string;
  compliance?: string;
  lastSyncDateTime?: string;
};

// A row that matched an existing serial and has at least one changed field.
// `data` is the exact column set to write; `loggedChanges` is the subset
// (deviceName/currentUserEmail) recorded to ItemEdit — telemetry updates silently.
export type ItemUpdate = {
  row: number;
  itemId: string;
  serialNumber: string;
  // `string | Date` because the derived `lastLogonAt` instant travels
  // alongside the raw `lastLogonDate` text it is parsed from.
  data: Record<string, string | Date | null>;
  loggedChanges: FieldChange[];
  makeModelMismatch: boolean;
};

export type UnchangedRow = { row: number; serialNumber: string; makeModelMismatch: boolean };

export type PlanResult = {
  toCreate: NewItemImport[];
  toUpdate: ItemUpdate[];
  unchanged: UnchangedRow[];
  skipped: SkippedRow[];
};

type ParsedImportRow = ReturnType<typeof importRowSchema.parse>;

/** One validated row, competing for its serial. */
type Candidate = {
  row: number;
  d: ParsedImportRow;
  sn: string;
  snKey: string;
  /** Parsed once here, reused by the winner. `null` when the export gave no
   *  usable date — which is a real state, not an error. */
  lastLogonAt: Date | null;
};

/**
 * Decide which of two rows carrying the SAME serial survives.
 *
 * A device that is re-imaged and re-enrolled appears twice in an MDM export:
 * the live record, and a stale enrollment nobody purged. This used to keep
 * whichever came first, which was correct only because the export happened to
 * be sorted newest-first — an incidental property of the exporting tool that
 * nothing here enforced or checked. A change of sort order would have started
 * writing months-old device names and holders into the property book silently.
 */
function preferredCandidate(a: Candidate, b: Candidate, serialIsNew: boolean): Candidate {
  // 1. USABILITY FIRST. Creating a new item requires make + model, so a fresher
  //    row missing them must not win: it would be rejected at the create branch
  //    below and take the only usable record for that serial down with it,
  //    dropping a device the old first-wins rule would have kept. A serial that
  //    already exists needs neither field, so this rule does not apply there.
  if (serialIsNew) {
    const aUsable = Boolean(a.d.make) && Boolean(a.d.model);
    const bUsable = Boolean(b.d.make) && Boolean(b.d.model);
    if (aUsable !== bUsable) return aUsable ? a : b;
  }
  // 2. A row MDM actually dated beats one it did not.
  if ((a.lastLogonAt === null) !== (b.lastLogonAt === null)) {
    return a.lastLogonAt !== null ? a : b;
  }
  // 3. Most recently seen wins.
  if (a.lastLogonAt && b.lastLogonAt && a.lastLogonAt.getTime() !== b.lastLogonAt.getTime()) {
    return a.lastLogonAt.getTime() > b.lastLogonAt.getTime() ? a : b;
  }
  // 4. Stable tie-break on the earlier row. Determinism matters beyond
  //    tidiness: the scheduled Drive import skips a byte-identical file by
  //    content hash, so a plan that varied between runs on the same input would
  //    make "unchanged" mean nothing.
  return a.row <= b.row ? a : b;
}

// Pure planning: validate each row (serial required), resolve duplicate serials
// within the file (the row MDM saw most recently wins — see preferredCandidate),
// then either UPDATE a matching existing item's changed tracked fields, mark it
// unchanged, or CREATE a new item (make/model required).
// homeUnit comes from the CSV column only — it is never derived from the
// device name (removed 2026-08-11; see the note in the matched branch).
export function planImport(
  rows: RawRow[],
  // Keyed by LOWERCASED serial by the caller — matching is case-insensitive (citext).
  existingBySerial: Map<string, ExistingItem>,
): PlanResult {
  const toCreate: NewItemImport[] = [];
  const toUpdate: ItemUpdate[] = [];
  const unchanged: UnchangedRow[] = [];
  const skipped: SkippedRow[] = [];

  // PHASE 1 — validate every row exactly once, in row order. Invalid rows are
  // rejected here, BEFORE any duplicate contest, so a malformed row can never
  // win one and take a usable duplicate of the same serial down with it.
  const candidates: Candidate[] = [];
  for (const r of rows) {
    const parsed = importRowSchema.safeParse({
      make: r.make,
      model: r.model,
      serialNumber: r.serialNumber,
      deviceName: r.deviceName,
      homeUnit: r.homeUnit,
      deviceUIC: r.deviceUIC,
      deviceCategory: r.deviceCategory,
      storageLocation: r.storageLocation,
      notes: r.notes,
      assignedUser: r.assignedUser,
      lastLogonUserPrincipalName: r.lastLogonUserPrincipalName,
      lastLogonDate: r.lastLogonDate,
      enrollmentDate: r.enrollmentDate,
      compliance: r.compliance,
      lastSyncDateTime: r.lastSyncDateTime,
    });
    if (!parsed.success) {
      skipped.push({ row: r.row, serialNumber: r.serialNumber, reason: parsed.error.issues[0]?.message ?? "invalid row" });
      continue;
    }
    const d = parsed.data;
    const sn = d.serialNumber;
    candidates.push({
      row: r.row,
      d,
      sn,
      snKey: sn.toLowerCase(),
      lastLogonAt: parseLastLogonAt(d.lastLogonDate) ?? null,
    });
  }

  // PHASE 2 — one winner per serial. Grouping preserves row order, so
  // `group[0]` is the first occurrence and the tie-break in preferredCandidate
  // reproduces the old first-wins behaviour whenever no row is demonstrably
  // fresher.
  const bySerial = new Map<string, Candidate[]>();
  for (const c of candidates) {
    const group = bySerial.get(c.snKey);
    if (group) group.push(c);
    else bySerial.set(c.snKey, [c]);
  }

  const winners = new Set<number>();
  for (const [snKey, group] of bySerial) {
    if (group.length === 1) {
      winners.add(group[0].row);
      continue;
    }
    const serialIsNew = !existingBySerial.has(snKey);
    const best = group.reduce((a, b) => preferredCandidate(a, b, serialIsNew));
    winners.add(best.row);

    // Name WHY the row lost. When the first occurrence won, nothing was chosen
    // on recency and the original wording is still the honest one.
    const reason = best.row === group[0].row
      ? "duplicate in file"
      : "duplicate in file (a row with a newer last logon was used)";
    for (const loser of group) {
      if (loser.row === best.row) continue;
      skipped.push({ row: loser.row, serialNumber: loser.sn, reason });
    }
  }

  // PHASE 3 — plan the winners, still in row order.
  for (const c of candidates) {
    if (!winners.has(c.row)) continue;
    const d = c.d;
    const sn = c.sn;
    const snKey = c.snKey;

    const match = existingBySerial.get(snKey);
    if (match) {
      // UPDATE / UNCHANGED path. make/model are never overwritten — only flagged.
      const makeModelMismatch = diffItemFields(match, {
        ...(d.make !== undefined ? { make: d.make } : {}),
        ...(d.model !== undefined ? { model: d.model } : {}),
      }).length > 0;

      // WITHHOLD an autogenerated rename. A re-enrolled device comes back named
      // `BE-` + 12 chars, and applying that destroys a meaningful name a person
      // put there. The stored name is kept and MDM's parked in mdmProposedName
      // for someone to action in Intune. Only when there is something better to
      // keep: if the stored name is itself autogenerated, or absent, MDM's newer
      // one is simply applied.
      const withholdRename =
        d.deviceName !== undefined &&
        isAutogeneratedDeviceName(d.deviceName) &&
        Boolean(match.deviceName) &&
        !isAutogeneratedDeviceName(match.deviceName);

      // Logged fields (deviceName, deviceUIC, currentUserEmail) -> ItemEdit history.
      const loggedAfter: Partial<ItemLoggedFields> = {};
      // Absent from loggedAfter when withheld, so diffItemFields reads it as
      // "not submitted": the column is not written and no history row is
      // produced for a rename that did not happen.
      if (d.deviceName !== undefined && !withholdRename) loggedAfter.deviceName = d.deviceName;
      // The rename flag is LOGGED, not silent.
      //
      // It shipped silent, on the reasoning that it is the importer's note to a
      // human rather than a custody fact. That was reversed deliberately
      // (2026-08-11): the item page offers the previous names behind a
      // disclosure, and `ItemEdit` is the only place a previous value of
      // anything is kept — a column overwritten in place remembers nothing. So
      // "MDM wanted to rename this and we refused" is recorded like any other
      // change to the device's identity.
      //
      // This is NOT the churn the telemetry fields are kept out of history to
      // avoid: `diffItemFields` emits only on an actual change, and this value
      // changes on three transitions only — flag raised, proposal superseded by
      // a different one, flag cleared. A steady state writes nothing.
      //
      // Written on EVERY matched row that supplied a name, not just withheld
      // ones, because the flag has to retract itself: `null` here clears a flag
      // left by an earlier import once MDM's name stops disagreeing. Absent
      // when the CSV carried no name at all, which is a "leave it alone".
      if (d.deviceName !== undefined) {
        loggedAfter.mdmProposedName = withholdRename ? d.deviceName : null;
      }
      if (d.deviceUIC !== undefined) loggedAfter.deviceUIC = d.deviceUIC;
      if (d.deviceCategory !== undefined) loggedAfter.deviceCategory = d.deviceCategory;
      if (d.storageLocation !== undefined) loggedAfter.storageLocation = d.storageLocation;
      if (d.assignedUser !== undefined) loggedAfter.currentUserEmail = d.assignedUser;

      // homeUnit comes from the CSV COLUMN and nowhere else. A supplied value
      // overwrites what is stored, exactly like deviceName/deviceUIC/
      // deviceCategory/the assigned user above; a blank cell leaves it alone,
      // because absent from loggedAfter reads as "not submitted".
      //
      // It used to be DERIVED from the device name when the column was blank —
      // decoding a unit abbreviation out of `HI-DCSIM-LT-001`. That is gone
      // (2026-08-11). It decoded every "-"/"_" segment, so an MDM-autogenerated
      // name like `BE-2AD6890X7IOL` matched a Unit named "BE" and rewrote the
      // device's home unit to "BE" — 18 devices ended up in that state, one of
      // them from "Safety Office". The measured value on the other side was one
      // device: the last full production import filled in exactly one home unit
      // by detection while corrupting eighteen. Devices with no home unit are
      // found on /admin/units ("Devices with no home unit"), which is a list of
      // what is actually missing rather than a guess from a hostname.
      if (d.homeUnit !== undefined) loggedAfter.homeUnit = d.homeUnit;
      const loggedChanges = diffItemFields(match, loggedAfter);

      // Silent telemetry fields -> updated but not logged.
      const silentAfter: Partial<ItemLoggedFields> = {};
      if (d.lastLogonUserPrincipalName !== undefined) silentAfter.lastLogonUserPrincipalName = d.lastLogonUserPrincipalName;
      if (d.lastLogonDate !== undefined) silentAfter.lastLogonDate = d.lastLogonDate;
      if (d.enrollmentDate !== undefined) silentAfter.enrollmentDate = d.enrollmentDate;
      if (d.compliance !== undefined) silentAfter.compliance = d.compliance;
      // Silent for a stronger reason than the rest: MDM syncs every device
      // most nights, so this value changes on nearly every row of nearly every
      // import. Logging it would write ~1,200 ItemEdit rows a night and bury
      // the custody edits the history exists to show.
      if (d.lastSyncDateTime !== undefined) silentAfter.lastSyncDateTime = d.lastSyncDateTime;

      const silentChanges = diffItemFields(match, silentAfter);

      const allChanges = [...loggedChanges, ...silentChanges];
      if (allChanges.length === 0) {
        unchanged.push({ row: c.row, serialNumber: sn, makeModelMismatch });
        continue;
      }
      const data: Record<string, string | Date | null> = {};
      for (const c of allChanges) data[c.field] = c.to;
      // Keep the parsed instant in step with the raw text. Readiness no longer
      // compares lastLogonAt to markedReadyAt (that rule was removed), but the
      // column still backs analytics and is what a reinstated rule would read —
      // so a refreshed lastLogonDate whose lastLogonAt went stale would leave
      // the two disagreeing about the same device.
      if (data.lastLogonDate !== undefined) {
        data.lastLogonAt = parseLastLogonAt(data.lastLogonDate as string | null);
      }
      // Retired items still get their fields updated (data holds every change),
      // but emit no loggedChanges so commitImport writes no ItemEdit for them.
      const emittedLogged = match.status === "RETIRED" ? [] : loggedChanges;
      toUpdate.push({ row: c.row, itemId: match.id, serialNumber: sn, data, loggedChanges: emittedLogged, makeModelMismatch });
      continue;
    }

    // CREATE path — make and model are required for a new item.
    if (!d.make || !d.model) {
      skipped.push({ row: c.row, serialNumber: sn, reason: "make and model are required for new items" });
      continue;
    }
    const item: NewItemImport = {
      make: d.make,
      model: d.model,
      serialNumber: sn,
      deviceName: d.deviceName,
      homeUnit: d.homeUnit,
      deviceUIC: d.deviceUIC,
      deviceCategory: d.deviceCategory,
      storageLocation: d.storageLocation,
      notes: d.notes,
      currentUserEmail: d.assignedUser,
      lastLogonUserPrincipalName: d.lastLogonUserPrincipalName,
      lastLogonDate: d.lastLogonDate,
      // Already parsed in phase 1 to decide duplicates; reused rather than
      // re-derived so the two can never disagree about the same row.
      lastLogonAt: c.lastLogonAt ?? undefined,
      enrollmentDate: d.enrollmentDate,
      compliance: d.compliance,
      lastSyncDateTime: d.lastSyncDateTime,
    };
    // No derivation here either — a new device's home unit comes from the CSV
    // column or stays blank. See the note in the matched branch above for why
    // decoding it from the device name was removed.
    toCreate.push(item);
  }

  // Duplicate losers are found in phase 2, before the winners are planned in
  // phase 3, so without this the report would list them out of order. Sorting
  // by row keeps it readable against the source file — which is how the 29
  // stale enrolments in the real export were actually tracked down.
  skipped.sort((a, b) => a.row - b.row);

  return { toCreate, toUpdate, unchanged, skipped };
}
