import { describe, it, expect } from "vitest";
import { planImport, isAutogeneratedDeviceName, type ExistingItem } from "./import";
import type { RawRow } from "./csv";

const UNITS = new Map<string, string>([["DCSIM", "DCSIM"], ["487B", "487FA BATTERY B"]]);

const mk = (row: number, over: Partial<RawRow> = {}): RawRow => ({
  row, make: "M4", model: "Carbine", serialNumber: `S${row}`, deviceName: "Radio",
  homeUnit: "", deviceUIC: "", deviceCategory: "", storageLocation: "", notes: "", assignedUser: "", lastLogonUserPrincipalName: "",
  lastLogonDate: "", enrollmentDate: "", compliance: "", lastSyncDateTime: "", ...over,
});

const existing = (over: Partial<ExistingItem> = {}): ExistingItem => ({
  id: "id-1", status: "ACTIVE", make: "M4", model: "Carbine", deviceName: "Radio", homeUnit: null, deviceUIC: null, deviceCategory: null, storageLocation: null, currentUserEmail: null,
  lastLogonUserPrincipalName: null, lastLogonDate: null, enrollmentDate: null, compliance: null,
  lastSyncDateTime: null, mdmProposedName: null, ...over,
});

const map = (serial: string, item: ExistingItem) => new Map([[serial.toLowerCase(), item]]);

describe("planImport", () => {
  it("creates new, non-duplicate rows", () => {
    const { toCreate, toUpdate, skipped } = planImport([mk(1), mk(2)], new Map(), UNITS);
    expect(toCreate).toHaveLength(2);
    expect(toUpdate).toHaveLength(0);
    expect(skipped).toHaveLength(0);
    expect(toCreate[0]).toMatchObject({ make: "M4", model: "Carbine", serialNumber: "S1" });
  });

  it("updates deviceName on a serial match (logged) and leaves make/model", () => {
    const { toUpdate, unchanged } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "NewName" })],
      map("A1", existing({ id: "x", deviceName: "OldName" })),
      UNITS,
    );
    expect(unchanged).toHaveLength(0);
    expect(toUpdate).toHaveLength(1);
    expect(toUpdate[0]).toMatchObject({ itemId: "x", serialNumber: "A1", makeModelMismatch: false });
    expect(toUpdate[0].data).toEqual({ deviceName: "NewName" });
    expect(toUpdate[0].loggedChanges).toEqual([{ field: "deviceName", from: "OldName", to: "NewName" }]);
  });

  it("updates assignedUser -> currentUserEmail (logged)", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", assignedUser: "jane@x.mil" })],
      map("A1", existing({ id: "x", currentUserEmail: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toEqual({ currentUserEmail: "jane@x.mil" });
    expect(toUpdate[0].loggedChanges).toEqual([{ field: "currentUserEmail", from: null, to: "jane@x.mil" }]);
  });

  it("updates deviceUIC on a serial match (logged)", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", deviceUIC: "WABC00" })],
      map("A1", existing({ id: "x", deviceUIC: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toEqual({ deviceUIC: "WABC00" });
    expect(toUpdate[0].loggedChanges).toEqual([{ field: "deviceUIC", from: null, to: "WABC00" }]);
  });

  it("updates telemetry silently (no loggedChanges)", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", compliance: "Compliant", lastLogonDate: "2026-07-01" })],
      map("A1", existing({ id: "x" })),
      UNITS,
    );
    // lastLogonAt rides along with the raw text it is parsed from: readiness
    // compares it to markedReadyAt, so a refreshed lastLogonDate whose parsed
    // instant went stale would leave a device reading "Ready" after it had
    // plainly been used again.
    expect(toUpdate[0].data).toEqual({
      compliance: "Compliant",
      lastLogonDate: "2026-07-01",
      lastLogonAt: new Date("2026-07-01T00:00:00.000Z"),
    });
    expect(toUpdate[0].loggedChanges).toEqual([]);
  });

  it("nulls the parsed instant when the incoming logon date is unparseable", () => {
    // The raw text is still stored for display, but readiness must fall back to
    // "we don't know when" rather than keep a stale instant from a prior import.
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", lastLogonDate: "not a date" })],
      map("A1", existing({ id: "x", lastLogonDate: "2026-07-01" })),
      UNITS,
    );
    expect(toUpdate[0].data.lastLogonDate).toBe("not a date");
    expect(toUpdate[0].data.lastLogonAt).toBeNull();
  });

  it("marks a fully-matching row unchanged", () => {
    const { toUpdate, unchanged } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "Radio" })],
      map("A1", existing({ id: "x", deviceName: "Radio" })),
      UNITS,
    );
    expect(toUpdate).toHaveLength(0);
    expect(unchanged).toEqual([{ row: 1, serialNumber: "A1", makeModelMismatch: false }]);
  });

  it("flags a make/model mismatch on a matched serial", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", make: "Dell", model: "5540", deviceName: "NewName" })],
      map("A1", existing({ id: "x", make: "M4", model: "Carbine", deviceName: "Old" })),
      UNITS,
    );
    expect(toUpdate[0].makeModelMismatch).toBe(true);
    expect(toUpdate[0].data).toEqual({ deviceName: "NewName" }); // make/model NOT written
  });

  it("blank assignedUser on a match leaves the stored value untouched", () => {
    const { toUpdate, unchanged } = planImport(
      [mk(1, { serialNumber: "A1", assignedUser: "" })],
      map("A1", existing({ id: "x", currentUserEmail: "keep@x.mil" })),
      UNITS,
    );
    expect(toUpdate).toHaveLength(0);
    expect(unchanged).toHaveLength(1);
  });

  it("never writes notes on a matched update, even when the CSV supplies it (out of scope for task 8)", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "NewName", notes: "some notes" })],
      map("A1", existing({ id: "x", deviceName: "Old" })),
      UNITS,
    );
    // deviceName changed -> it's an update; notes is still ignored on a match.
    expect(toUpdate[0].data).toEqual({ deviceName: "NewName" });
    expect(toUpdate[0].data).not.toHaveProperty("notes");
  });

  // --- homeUnit on a matched (UPDATE) row — task 8: the CSV import is the
  // single source of truth for homeUnit, including on rows that already exist.

  it("matched row, blank stored homeUnit, CSV supplies one -> stored verbatim, logged, not counted as detected", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", homeUnit: "456th Signal Co" })],
      map("A1", existing({ id: "x", homeUnit: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "456th Signal Co" });
    expect(toUpdate[0].loggedChanges).toContainEqual({ field: "homeUnit", from: null, to: "456th Signal Co" });
    expect(detected).toBe(0);
  });

  it("matched row, blank stored, no CSV value, device name decodes -> filled from detectHomeUnit, detected incremented", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-DCSIM-LT-001" })],
      map("A1", existing({ id: "x", deviceName: "HI-DCSIM-LT-001", homeUnit: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "DCSIM" });
    expect(detected).toBe(1);
  });

  it("matched row, stored homeUnit already equals what detectHomeUnit derives -> NOT counted as detected, no homeUnit change", () => {
    // Regression test: the nightly full-fleet CSV carries no homeUnit column, so
    // nearly every matched row re-derives the value it already has. `detected`
    // must not fire just because detection SUCCEEDED — only when it actually
    // changed the stored value.
    const { toUpdate, unchanged, detected } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-DCSIM-LT-001" })],
      map("A1", existing({ id: "x", deviceName: "HI-DCSIM-LT-001", homeUnit: "DCSIM" })),
      UNITS,
    );
    expect(detected).toBe(0);
    expect(toUpdate).toHaveLength(0);
    expect(unchanged).toEqual([{ row: 1, serialNumber: "A1", makeModelMismatch: false }]);
  });

  it("matched row, stored homeUnit differs from what detectHomeUnit derives (no CSV value) -> corrected, detected incremented", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-DCSIM-LT-001" })],
      map("A1", existing({ id: "x", deviceName: "HI-DCSIM-LT-001", homeUnit: "Some Other Unit" })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "DCSIM" });
    expect(toUpdate[0].loggedChanges).toContainEqual({ field: "homeUnit", from: "Some Other Unit", to: "DCSIM" });
    expect(detected).toBe(1);
  });

  it("matched row with a NON-blank stored value and a different CSV value -> OVERWRITTEN with the CSV value, change logged", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", homeUnit: "New Unit" })],
      map("A1", existing({ id: "x", homeUnit: "Old Unit" })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "New Unit" });
    expect(toUpdate[0].loggedChanges).toContainEqual({ field: "homeUnit", from: "Old Unit", to: "New Unit" });
    expect(detected).toBe(0);
  });

  it("matched row, blank stored, device name does not decode -> unchanged, appears in unresolved", () => {
    const { toUpdate, unchanged, unresolved } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-XYZ-LT-001" })],
      map("A1", existing({ id: "x", deviceName: "HI-XYZ-LT-001", homeUnit: null })),
      UNITS,
    );
    expect(toUpdate).toHaveLength(0);
    expect(unchanged).toEqual([{ row: 1, serialNumber: "A1", makeModelMismatch: false }]);
    expect(unresolved).toEqual([{ row: 1, deviceName: "HI-XYZ-LT-001", segments: ["HI", "XYZ", "LT", "001"] }]);
  });

  it("matched row, blank stored, no device name at all -> unchanged, NOT in unresolved", () => {
    const { toUpdate, unchanged, unresolved } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "" })],
      map("A1", existing({ id: "x", deviceName: null, homeUnit: null })),
      UNITS,
    );
    expect(toUpdate).toHaveLength(0);
    expect(unchanged).toEqual([{ row: 1, serialNumber: "A1", makeModelMismatch: false }]);
    expect(unresolved).toHaveLength(0);
  });

  it("effective device name: stored name does not decode, CSV supplies one that does -> filled", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-DCSIM-LT-001" })],
      map("A1", existing({ id: "x", deviceName: "HI-XYZ-LT-001", homeUnit: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "DCSIM" });
    expect(detected).toBe(1);
  });

  it("CSV homeUnit that is whitespace-only is treated as blank and falls through to detection", () => {
    const { toUpdate, detected } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "HI-DCSIM-LT-001", homeUnit: "   " })],
      map("A1", existing({ id: "x", deviceName: "HI-DCSIM-LT-001", homeUnit: null })),
      UNITS,
    );
    expect(toUpdate[0].data).toMatchObject({ homeUnit: "DCSIM" });
    expect(detected).toBe(1);
  });

  it("updates a RETIRED item's fields but emits no loggedChanges (no history row)", () => {
    const { toUpdate } = planImport(
      [mk(1, { serialNumber: "A1", deviceName: "NewName", assignedUser: "jane@x.mil", compliance: "Compliant" })],
      map("A1", existing({ id: "x", status: "RETIRED", deviceName: "Old", currentUserEmail: null })),
      UNITS,
    );
    expect(toUpdate).toHaveLength(1);
    // Fields still update (data carries every change)...
    expect(toUpdate[0].data).toEqual({ deviceName: "NewName", currentUserEmail: "jane@x.mil", compliance: "Compliant" });
    // ...but no ItemEdit history is written for a retired item.
    expect(toUpdate[0].loggedChanges).toEqual([]);
  });

  it("skips a new row missing make or model", () => {
    const { toCreate, skipped } = planImport([mk(1, { serialNumber: "N1", make: "" })], new Map(), UNITS);
    expect(toCreate).toHaveLength(0);
    expect(skipped).toEqual([{ row: 1, serialNumber: "N1", reason: "make and model are required for new items" }]);
  });

  it("skips a row with a blank serial", () => {
    const { skipped } = planImport([mk(1, { serialNumber: "" })], new Map(), UNITS);
    expect(skipped[0].reason).toMatch(/serial number is required/i);
  });

  it("treats serials differing only in case as the same device within a file", () => {
    const { toCreate, skipped } = planImport(
      [mk(1, { serialNumber: "AbC123" }), mk(2, { serialNumber: "abc123" })],
      new Map(), UNITS,
    );
    expect(toCreate).toHaveLength(1);
    expect(skipped).toEqual([{ row: 2, serialNumber: "abc123", reason: "duplicate in file" }]);
  });

  // A device re-imaged and re-enrolled appears TWICE in the MDM export under the
  // same serial: the live record, and a stale enrollment nobody purged. Measured
  // on the real fleet export (2026-08-11): 29 such serials, every pair
  // disagreeing, the two records 4-208 days apart (median 41). Keeping the first
  // occurrence was only correct because that export happened to be sorted
  // newest-first; nothing enforced that, so a change of export sort order would
  // have silently started writing months-old device names and holders into the
  // property book with no error anywhere.
  describe("duplicate serials in one file", () => {
    const logon = (row: number, serial: string, date: string, over: Partial<RawRow> = {}) =>
      mk(row, { serialNumber: serial, lastLogonDate: date, ...over });

    it("keeps the row MDM saw most recently, not the first one", () => {
      const { toUpdate, skipped } = planImport(
        [
          logon(1, "DUP", "5/14/2026 3:27:36 PM", { deviceName: "OLD-NAME" }),
          logon(2, "DUP", "8/10/2026 9:19:17 PM", { deviceName: "NEW-NAME" }),
        ],
        map("DUP", existing({ deviceName: "OLD-NAME" })),
        UNITS,
      );
      expect(toUpdate).toHaveLength(1);
      expect(toUpdate[0].data.deviceName).toBe("NEW-NAME");
      expect(skipped).toEqual([
        { row: 1, serialNumber: "DUP", reason: "duplicate in file (a row with a newer last logon was used)" },
      ]);
    });

    it("still keeps the newest when it comes first", () => {
      const { toUpdate, skipped } = planImport(
        [
          logon(1, "DUP", "8/10/2026 9:19:17 PM", { deviceName: "NEW-NAME" }),
          logon(2, "DUP", "5/14/2026 3:27:36 PM", { deviceName: "OLD-NAME" }),
        ],
        map("DUP", existing({ deviceName: "OLD-NAME" })),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe("NEW-NAME");
      expect(skipped[0].row).toBe(2);
    });

    it("renames the device to the newest record's name and logs the change", () => {
      const { toUpdate } = planImport(
        [
          logon(1, "DUP", "1/02/2026 1:00:00 AM", { deviceName: "BE-UV2ZGBPHR0FL" }),
          logon(2, "DUP", "8/10/2026 1:00:00 AM", { deviceName: "NGHINBPMTEL274" }),
        ],
        map("DUP", existing({ deviceName: "BE-UV2ZGBPHR0FL" })),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe("NGHINBPMTEL274");
      expect(toUpdate[0].loggedChanges).toEqual(
        expect.arrayContaining([expect.objectContaining({ field: "deviceName" })]),
      );
    });

    it("prefers a row that HAS a last-logon date over one that has none", () => {
      const { toUpdate, skipped } = planImport(
        [
          mk(1, { serialNumber: "DUP", deviceName: "NO-DATE", lastLogonDate: "" }),
          logon(2, "DUP", "8/10/2026 9:19:17 PM", { deviceName: "HAS-DATE" }),
        ],
        map("DUP", existing()),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe("HAS-DATE");
      expect(skipped[0].row).toBe(1);
    });

    // Unchanged from the original behaviour, and the reason string stays the
    // plain one so it still reads correctly: nothing "newer" was chosen.
    it("falls back to first-wins when neither row has a usable date", () => {
      const { toCreate, skipped } = planImport(
        [mk(1, { serialNumber: "AbC123" }), mk(2, { serialNumber: "abc123" })],
        new Map(), UNITS,
      );
      expect(toCreate).toHaveLength(1);
      expect(skipped).toEqual([{ row: 2, serialNumber: "abc123", reason: "duplicate in file" }]);
    });

    it("breaks an exact date tie on the earlier row, so a re-run is stable", () => {
      const { skipped } = planImport(
        [logon(1, "DUP", "8/10/2026 9:19:17 PM"), logon(2, "DUP", "8/10/2026 9:19:17 PM")],
        map("DUP", existing()),
        UNITS,
      );
      expect(skipped[0].row).toBe(2);
    });

    it("matches duplicates case-insensitively, like the citext serial column", () => {
      const { toUpdate, skipped } = planImport(
        [
          logon(1, "abc123", "1/02/2026 1:00:00 AM", { deviceName: "OLD" }),
          logon(2, "ABC123", "8/10/2026 1:00:00 AM", { deviceName: "NEW" }),
        ],
        map("abc123", existing()),
        UNITS,
      );
      expect(toUpdate).toHaveLength(1);
      expect(toUpdate[0].data.deviceName).toBe("NEW");
      expect(skipped).toHaveLength(1);
    });

    // Without this, a newest-wins rule could DROP A DEVICE the old first-wins
    // rule would have created: make/model are required to create, so crowning a
    // fresher row that lacks them loses the only usable record for that serial.
    it("does not let a fresher row without make/model lose a NEW serial entirely", () => {
      const { toCreate, skipped } = planImport(
        [
          logon(1, "NEWSN", "1/02/2026 1:00:00 AM", { make: "Dell", model: "5540" }),
          logon(2, "NEWSN", "8/10/2026 1:00:00 AM", { make: "", model: "" }),
        ],
        new Map(),
        UNITS,
      );
      expect(toCreate).toHaveLength(1);
      expect(toCreate[0]).toMatchObject({ serialNumber: "NEWSN", make: "Dell", model: "5540" });
      expect(skipped).toHaveLength(1);
    });

    // For a serial that ALREADY exists, make/model are not required, so the
    // freshest row wins even when it carries neither.
    it("still takes the freshest row for an EXISTING serial without make/model", () => {
      const { toUpdate } = planImport(
        [
          logon(1, "DUP", "1/02/2026 1:00:00 AM", { deviceName: "OLD", make: "Dell", model: "5540" }),
          logon(2, "DUP", "8/10/2026 1:00:00 AM", { deviceName: "NEW", make: "", model: "" }),
        ],
        map("DUP", existing({ deviceName: "OLD" })),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe("NEW");
    });

    it("reports skipped rows sorted by row number", () => {
      const { skipped } = planImport(
        [
          logon(1, "A", "8/10/2026 1:00:00 AM"),
          mk(2, { serialNumber: "" }),
          logon(3, "A", "1/02/2026 1:00:00 AM"),
        ],
        map("a", existing()),
        UNITS,
      );
      expect(skipped.map((s) => s.row)).toEqual([2, 3]);
    });

    it("handles three copies of one serial, keeping only the newest", () => {
      const { toUpdate, skipped } = planImport(
        [
          logon(1, "DUP", "1/02/2026 1:00:00 AM", { deviceName: "A" }),
          logon(2, "DUP", "8/10/2026 1:00:00 AM", { deviceName: "B" }),
          logon(3, "DUP", "4/01/2026 1:00:00 AM", { deviceName: "C" }),
        ],
        map("DUP", existing()),
        UNITS,
      );
      expect(toUpdate).toHaveLength(1);
      expect(toUpdate[0].data.deviceName).toBe("B");
      expect(skipped.map((s) => s.row)).toEqual([1, 3]);
    });
  });

  // An MDM re-enrolment renames a device to an autogenerated string
  // ("BE-" + 12 chars). Applying that replaced meaningful names like
  // NGHINBPMACN128 with BE-7J5AKRNFLP6B in production, and — because
  // detectHomeUnit decodes the leading segment — also wrote "BE" into homeUnit
  // for 18 devices. The rename is withheld and reported instead.
  describe("autogenerated MDM device names", () => {
    const UNITS_WITH_BE = new Map<string, string>([...UNITS, ["BE", "BE"]]);
    const AUTO = "BE-7J5AKRNFLP6B";

    it("recognises the autogenerated shape and nothing else", () => {
      expect(isAutogeneratedDeviceName("BE-7J5AKRNFLP6B")).toBe(true);
      expect(isAutogeneratedDeviceName("BE-2AD6890X7IOL")).toBe(true);
      // Real names, and near-misses that must NOT be swallowed by the rule.
      expect(isAutogeneratedDeviceName("NGHINBPMACN128")).toBe(false);
      expect(isAutogeneratedDeviceName("BE-SHORT")).toBe(false);
      expect(isAutogeneratedDeviceName("BEX-7J5AKRNFLP6B")).toBe(false);
      expect(isAutogeneratedDeviceName("BE-7J5AKRNFLP6BX")).toBe(false);
      expect(isAutogeneratedDeviceName("be-7j5akrnflp6b")).toBe(false);
      expect(isAutogeneratedDeviceName(null)).toBe(false);
      expect(isAutogeneratedDeviceName("")).toBe(false);
    });

    it("keeps the real name and records the one MDM wanted", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO })],
        map("S1", existing({ deviceName: "NGHINBPMACN128" })),
        UNITS,
      );
      expect(toUpdate).toHaveLength(1);
      // The name column is NOT written.
      expect(toUpdate[0].data.deviceName).toBeUndefined();
      expect(toUpdate[0].data.mdmProposedName).toBe(AUTO);
    });

    it("writes NO history row for a withheld rename", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO })],
        map("S1", existing({ deviceName: "NGHINBPMACN128" })),
        UNITS,
      );
      // mdmProposedName is a note to a human, not a custody fact — it must not
      // appear in the item's edit history, and neither must a rename that
      // never happened.
      expect(toUpdate[0].loggedChanges).toEqual([]);
    });

    // THE contamination fix. Without it, detectHomeUnit reads "BE" out of the
    // autogenerated name and a Unit row named BE (which exists in production)
    // turns the device's home unit into "BE".
    it("derives homeUnit from the STORED name, not the withheld one", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO, homeUnit: "" })],
        map("S1", existing({ deviceName: "HI-DCSIM-LT-001", homeUnit: null })),
        UNITS_WITH_BE,
      );
      expect(toUpdate[0].data.homeUnit).toBe("DCSIM");
      expect(toUpdate[0].data.homeUnit).not.toBe("BE");
    });

    it("accepts the autogenerated name when the stored name is autogenerated too", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO })],
        map("S1", existing({ deviceName: "BE-S64IL5PDENAZ" })),
        UNITS,
      );
      // Nothing better to keep, so MDM's newer name wins and no flag is raised.
      expect(toUpdate[0].data.deviceName).toBe(AUTO);
      expect(toUpdate[0].data.mdmProposedName).toBeUndefined();
    });

    it("accepts it when the item has no stored name at all", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO })],
        map("S1", existing({ deviceName: null })),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe(AUTO);
    });

    it("applies a real name normally and raises no flag", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: "NGHINBPMTEL284" })],
        map("S1", existing({ deviceName: "NGHINBPMACN128" })),
        UNITS,
      );
      expect(toUpdate[0].data.deviceName).toBe("NGHINBPMTEL284");
      expect(toUpdate[0].loggedChanges).toEqual(
        expect.arrayContaining([expect.objectContaining({ field: "deviceName" })]),
      );
    });

    // The flag has to retract itself, or a device renamed properly in Intune
    // stays on the worklist for ever.
    it("clears the flag once MDM stops disagreeing", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: "NGHINBPMTEL284" })],
        map("S1", existing({ deviceName: "NGHINBPMACN128", mdmProposedName: AUTO })),
        UNITS,
      );
      expect(toUpdate[0].data.mdmProposedName).toBeNull();
    });

    it("does not rewrite a flag that is already correct", () => {
      const { toUpdate, unchanged } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO })],
        map("S1", existing({ deviceName: "NGHINBPMACN128", mdmProposedName: AUTO })),
        UNITS,
      );
      // Nothing changed at all, so this is an unchanged row and not an update.
      expect(toUpdate).toHaveLength(0);
      expect(unchanged).toHaveLength(1);
    });

    // A brand-new serial has no stored name to protect, so there is nothing to
    // withhold — the device is created under whatever MDM calls it.
    it("creates a NEW device under an autogenerated name without flagging it", () => {
      const { toCreate } = planImport(
        [mk(1, { serialNumber: "NEW1", deviceName: AUTO })],
        new Map(), UNITS,
      );
      expect(toCreate).toHaveLength(1);
      expect(toCreate[0].deviceName).toBe(AUTO);
    });

    // The withhold guard alone does NOT stop the homeUnit damage, because it
    // only fires when there is a real stored name to protect. detectHomeUnit
    // scans EVERY "-"/"_" segment, so "BE-2AD6890X7IOL" matches a Unit named
    // "BE" on two paths the guard never reaches: a brand-new serial, and a
    // matched row with no stored name.
    //
    // Worse, the recurrence path is a feature: an undecodable name lands in
    // `unresolved`, and /admin/items/import asks an admin to pick a segment and
    // NAME it — which is exactly how the production "BE" unit came to exist.
    // Leaving autogenerated names in that list invites someone to recreate the
    // bug by hand. An autogenerated name carries no unit information at all, so
    // it is neither decoded nor offered for decoding.
    it("does not derive a homeUnit from an autogenerated name on CREATE", () => {
      const { toCreate, detected } = planImport(
        [mk(1, { serialNumber: "NEW1", deviceName: AUTO, homeUnit: "" })],
        new Map(), UNITS_WITH_BE,
      );
      expect(toCreate).toHaveLength(1);
      expect(toCreate[0].homeUnit).toBeUndefined();
      expect(detected).toBe(0);
    });

    it("does not offer an autogenerated name for unit resolution on CREATE", () => {
      const { unresolved } = planImport(
        [mk(1, { serialNumber: "NEW1", deviceName: AUTO, homeUnit: "" })],
        new Map(), UNITS_WITH_BE,
      );
      expect(unresolved).toEqual([]);
    });

    it("does not derive a homeUnit from an autogenerated name when the item has no stored name", () => {
      const { toUpdate } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO, homeUnit: "" })],
        map("S1", existing({ deviceName: null, homeUnit: null })),
        UNITS_WITH_BE,
      );
      // The name is applied (nothing better to keep), but it must not be
      // decoded into a unit.
      expect(toUpdate[0]?.data.deviceName).toBe(AUTO);
      expect(toUpdate[0]?.data.homeUnit).toBeUndefined();
    });

    it("does not offer an autogenerated name for unit resolution on a matched row", () => {
      const { unresolved } = planImport(
        [mk(1, { serialNumber: "S1", deviceName: AUTO, homeUnit: "" })],
        map("S1", existing({ deviceName: null, homeUnit: null })),
        UNITS_WITH_BE,
      );
      expect(unresolved).toEqual([]);
    });

    // Regression guard: a real name must still decode exactly as before.
    it("still derives a homeUnit from a REAL device name", () => {
      const { toCreate, detected } = planImport(
        [mk(1, { serialNumber: "NEW1", deviceName: "HI-DCSIM-LT-001", homeUnit: "" })],
        new Map(), UNITS_WITH_BE,
      );
      expect(toCreate[0].homeUnit).toBe("DCSIM");
      expect(detected).toBe(1);
    });

    it("still withholds when the winning duplicate row carries the autogenerated name", () => {
      const { toUpdate } = planImport(
        [
          mk(1, { serialNumber: "S1", deviceName: "NGHINBPMACN128", lastLogonDate: "1/02/2026 1:00:00 AM" }),
          mk(2, { serialNumber: "S1", deviceName: AUTO, lastLogonDate: "8/10/2026 1:00:00 AM" }),
        ],
        map("S1", existing({ deviceName: "NGHINBPMACN128" })),
        UNITS,
      );
      // Row 2 wins on recency, but its name is autogenerated, so the stored
      // name survives and the proposal is recorded.
      expect(toUpdate[0].data.deviceName).toBeUndefined();
      expect(toUpdate[0].data.mdmProposedName).toBe(AUTO);
    });
  });

  it("auto-fills homeUnit from the device name on create when blank", () => {
    const { toCreate, detected } = planImport(
      [mk(1, { deviceName: "HI-DCSIM-LT-001", homeUnit: "" })], new Map(), UNITS,
    );
    expect(toCreate[0].homeUnit).toBe("DCSIM");
    expect(detected).toBe(1);
  });

  it("reports unresolved device names on create", () => {
    const { unresolved } = planImport(
      [mk(1, { deviceName: "HI-XYZ-LT-001", homeUnit: "" })], new Map(), UNITS,
    );
    expect(unresolved).toEqual([{ row: 1, deviceName: "HI-XYZ-LT-001", segments: ["HI", "XYZ", "LT", "001"] }]);
  });
});

describe("lastSyncDateTime", () => {
  it("sets it on a newly created item", () => {
    const plan = planImport([mk(1, { lastSyncDateTime: "8/9/2026 6:02:11 AM" })], new Map(), UNITS);
    expect(plan.toCreate[0]?.lastSyncDateTime).toBe("8/9/2026 6:02:11 AM");
  });

  it("updates a matched row SILENTLY — no ItemEdit history", () => {
    // The load-bearing one. MDM syncs nearly every device nightly, so this
    // value changes on nearly every row of nearly every import; logging it
    // would write ~1,200 history rows a night and bury the custody edits the
    // ItemEdit trail exists to show. It must land in `data` (so the column is
    // written) while staying out of `loggedChanges`.
    const before = existing({ lastSyncDateTime: "8/1/2026 1:00:00 AM" });
    const plan = planImport(
      [mk(1, { serialNumber: "S1", lastSyncDateTime: "8/9/2026 6:02:11 AM" })],
      map("S1", before),
      UNITS,
    );
    expect(plan.toUpdate[0]?.data.lastSyncDateTime).toBe("8/9/2026 6:02:11 AM");
    expect(plan.toUpdate[0]?.loggedChanges.map((c) => c.field)).not.toContain("lastSyncDateTime");
  });

  it("counts as a real change, so a row whose ONLY difference is the sync time is not 'unchanged'", () => {
    // Silent is not the same as ignored: the column still has to be written,
    // which means the row belongs in toUpdate rather than in unchanged.
    const before = existing({ lastSyncDateTime: "8/1/2026 1:00:00 AM" });
    const plan = planImport(
      [mk(1, { serialNumber: "S1", lastSyncDateTime: "8/9/2026 6:02:11 AM" })],
      map("S1", before),
      UNITS,
    );
    expect(plan.toUpdate).toHaveLength(1);
    expect(plan.unchanged).toHaveLength(0);
  });

  it("leaves the stored value untouched when the cell is blank", () => {
    const before = existing({ lastSyncDateTime: "8/1/2026 1:00:00 AM" });
    const plan = planImport([mk(1, { serialNumber: "S1", lastSyncDateTime: "" })], map("S1", before), UNITS);
    expect(plan.unchanged).toHaveLength(1);
    expect(plan.toUpdate).toHaveLength(0);
  });

  it("does not disturb lastLogonDate or its parsed twin", () => {
    // The two are separate facts. A sync-only refresh must not touch the logon
    // columns — lastLogonAt in particular is what readiness would read.
    const before = existing({ lastLogonDate: "7/25/2026 1:40:21 AM", lastSyncDateTime: null });
    const plan = planImport(
      [mk(1, { serialNumber: "S1", lastLogonDate: "", lastSyncDateTime: "8/9/2026 6:02:11 AM" })],
      map("S1", before),
      UNITS,
    );
    expect(plan.toUpdate[0]?.data.lastSyncDateTime).toBe("8/9/2026 6:02:11 AM");
    expect(plan.toUpdate[0]?.data).not.toHaveProperty("lastLogonDate");
    expect(plan.toUpdate[0]?.data).not.toHaveProperty("lastLogonAt");
  });
});

describe("storageLocation", () => {
  it("sets it on a newly created item", () => {
    const rows = [{ row: 1, make: "Dell", model: "5540", serialNumber: "NEW-1", deviceName: "", homeUnit: "", deviceUIC: "", deviceCategory: "", storageLocation: "Bldg 400 Cage 3", notes: "", assignedUser: "", lastLogonUserPrincipalName: "", lastLogonDate: "", enrollmentDate: "", compliance: "", lastSyncDateTime: "" }];
    const plan = planImport(rows, new Map(), new Map());
    expect(plan.toCreate[0]?.storageLocation).toBe("Bldg 400 Cage 3");
  });

  it("OVERWRITES the stored value on a matched row, and logs the change", () => {
    const existing = new Map([["old-1", {
      id: "i1", status: "ACTIVE", make: "Dell", model: "5540", deviceName: "N1",
      homeUnit: null, deviceUIC: null, deviceCategory: null, storageLocation: "Bldg 400",
      currentUserEmail: null, lastLogonUserPrincipalName: null, lastLogonDate: null,
      enrollmentDate: null, compliance: null, lastSyncDateTime: null, mdmProposedName: null,
    }]]);
    const rows = [{ row: 1, make: "", model: "", serialNumber: "OLD-1", deviceName: "", homeUnit: "", deviceUIC: "", deviceCategory: "", storageLocation: "Bldg 401", notes: "", assignedUser: "", lastLogonUserPrincipalName: "", lastLogonDate: "", enrollmentDate: "", compliance: "", lastSyncDateTime: "" }];
    const plan = planImport(rows, existing, new Map());
    expect(plan.toUpdate[0]?.data.storageLocation).toBe("Bldg 401");
    expect(plan.toUpdate[0]?.loggedChanges).toContainEqual({ field: "storageLocation", from: "Bldg 400", to: "Bldg 401" });
  });

  it("leaves the stored value untouched when the cell is blank", () => {
    const existing = new Map([["old-2", {
      id: "i2", status: "ACTIVE", make: "Dell", model: "5540", deviceName: "N2",
      homeUnit: null, deviceUIC: null, deviceCategory: null, storageLocation: "Bldg 400",
      currentUserEmail: null, lastLogonUserPrincipalName: null, lastLogonDate: null,
      enrollmentDate: null, compliance: null, lastSyncDateTime: null, mdmProposedName: null,
    }]]);
    const rows = [{ row: 1, make: "", model: "", serialNumber: "OLD-2", deviceName: "", homeUnit: "", deviceUIC: "", deviceCategory: "", storageLocation: "", notes: "", assignedUser: "", lastLogonUserPrincipalName: "", lastLogonDate: "", enrollmentDate: "", compliance: "", lastSyncDateTime: "" }];
    const plan = planImport(rows, existing, new Map());
    expect(plan.unchanged).toHaveLength(1);
    expect(plan.toUpdate).toHaveLength(0);
  });

  it("writes no history row for a RETIRED item, but still updates the column", () => {
    const existing = new Map([["ret-1", {
      id: "i3", status: "RETIRED", make: "Dell", model: "5540", deviceName: "N3",
      homeUnit: null, deviceUIC: null, deviceCategory: null, storageLocation: "Bldg 400",
      currentUserEmail: null, lastLogonUserPrincipalName: null, lastLogonDate: null,
      enrollmentDate: null, compliance: null, lastSyncDateTime: null, mdmProposedName: null,
    }]]);
    const rows = [{ row: 1, make: "", model: "", serialNumber: "RET-1", deviceName: "", homeUnit: "", deviceUIC: "", deviceCategory: "", storageLocation: "Bldg 401", notes: "", assignedUser: "", lastLogonUserPrincipalName: "", lastLogonDate: "", enrollmentDate: "", compliance: "", lastSyncDateTime: "" }];
    const plan = planImport(rows, existing, new Map());
    expect(plan.toUpdate[0]?.data.storageLocation).toBe("Bldg 401");
    expect(plan.toUpdate[0]?.loggedChanges).toEqual([]);
  });
});
