import { describe, expect, it } from "vitest";
import { isLoanerName, loanerUpdateForRename } from "./loaner-name";

describe("isLoanerName", () => {
  it("matches the fleet's convention", () => {
    // The exact shapes in production: 51 devices, numbered 001-139.
    for (const n of ["NGHINB-LOAN-001", "NGHINB-LOAN-091", "NGHINB-LOAN-139"]) {
      expect(isLoanerName(n), n).toBe(true);
    }
  });

  it("accepts any number of digits, not just three", () => {
    // The numbering has already reached 139; a loaner numbered 1000 silently
    // ceasing to be one is worse than a two-digit name being accepted.
    expect(isLoanerName("NGHINB-LOAN-7")).toBe(true);
    expect(isLoanerName("NGHINB-LOAN-1000")).toBe(true);
  });

  it("ignores case and surrounding whitespace", () => {
    // Deliberately unlike isAutogeneratedDeviceName, which is case-sensitive.
    // This is a convention a person types by hand.
    expect(isLoanerName("nghinb-loan-140")).toBe(true);
    expect(isLoanerName("  NGHINB-Loan-012  ")).toBe(true);
  });

  it("is ANCHORED — a name that merely contains the word does not match", () => {
    for (const n of [
      "NGHINB-LOANER-DEPOT",
      "OLD-NGHINB-LOAN-001",
      "NGHINB-LOAN-001-SPARE",
      "NGHINB-LOAN-",
      "NGHINB-LOAN-ABC",
      "LOAN-001",
    ]) {
      expect(isLoanerName(n), n).toBe(false);
    }
  });

  it("handles a device with no name", () => {
    expect(isLoanerName(null)).toBe(false);
    expect(isLoanerName(undefined)).toBe(false);
    expect(isLoanerName("")).toBe(false);
  });

  it("does not match an MDM-autogenerated name", () => {
    // A re-enrolled loaner comes back as BE-XXXXXXXXXXXX. The importer WITHHOLDS
    // that rename, so the stored name stays NGHINB-LOAN-### and the flag stays
    // — but if the guard were ever removed, this is what would clear it.
    expect(isLoanerName("BE-7J5AKRNFLP6B")).toBe(false);
  });
});

describe("loanerUpdateForRename", () => {
  it("sets the flag when a name moves INTO the convention", () => {
    expect(loanerUpdateForRename("NGHINB-PMACN128", "NGHINB-LOAN-140")).toEqual({ isLoaner: true });
    expect(loanerUpdateForRename(null, "NGHINB-LOAN-140")).toEqual({ isLoaner: true });
  });

  it("clears the flag when a name moves OUT of the convention", () => {
    expect(loanerUpdateForRename("NGHINB-LOAN-001", "NGHINB-PMACN128")).toEqual({ isLoaner: false });
    expect(loanerUpdateForRename("NGHINB-LOAN-001", null)).toEqual({ isLoaner: false });
  });

  it("LEAVES A HAND-SET FLAG ALONE when neither name follows the convention", () => {
    // The load-bearing case. The admin toggle still works on devices outside
    // the naming convention, and an unrelated rename must not switch it off:
    // NGHINB-PMACN128 -> NGHINB-PMACN129 is evidence about nothing.
    expect(loanerUpdateForRename("NGHINB-PMACN128", "NGHINB-PMACN129")).toEqual({});
    expect(loanerUpdateForRename(null, "NGHINB-SWITCH-04")).toEqual({});
    expect(loanerUpdateForRename(null, null)).toEqual({});
  });

  it("stays set when a loaner is renumbered within the convention", () => {
    expect(loanerUpdateForRename("NGHINB-LOAN-001", "NGHINB-LOAN-002")).toEqual({ isLoaner: true });
  });

  it("reads the NAMES, never the current flag", () => {
    // Inferring the transition from `isLoaner` instead would re-assert false
    // over a hand-set true every time any field on a non-matching device was
    // edited. The signature makes that mistake unavailable.
    expect(loanerUpdateForRename("A", "B")).toEqual({});
  });
});
