/**
 * The loaner NAMING CONVENTION, and what a rename does to `Item.isLoaner`.
 *
 * Pure — no Prisma, no React — so the rule can be unit-tested directly and
 * imported by every path that writes a device name, the same reason
 * `readiness.ts` and `audit.status.ts` are split out.
 *
 * WHY THIS EXISTS AT ALL, given the column says otherwise. `isLoaner` shipped
 * (2026-08-11, #129) as a purely hand-set flag, and its schema comment said a
 * person was "the only possible source" precisely so a nightly import could not
 * move it. That was reversed the same day by explicit decision: the property
 * manager already encodes loaner status IN THE DEVICE NAME — 51 devices are
 * named `NGHINB-LOAN-###` — and maintaining the same fact twice, once in Intune
 * and once here, is what guarantees the two disagree. The convention is now the
 * source, and the schema comment has been corrected rather than left lying.
 *
 * THE CONSEQUENCE, stated plainly because it is the cost of the decision: MDM
 * owns `deviceName`, so MDM now indirectly owns `isLoaner` for any device whose
 * name matches or stops matching. A device renamed in Intune out of the loaner
 * convention loses the flag on the next import without anyone here deciding
 * that.
 */

/**
 * `NGHINB-LOAN-` followed by digits.
 *
 * ANCHORED, so a name that merely CONTAINS the word cannot match — the fleet
 * has no such names today (measured: 51 match this exactly, 0 others contain
 * "loan"), and a substring rule would eventually catch something like
 * `NGHINB-LOANER-DEPOT`.
 *
 * DIGITS ARE `+`, NOT `{3}`, even though all 51 are three digits today. The
 * numbering has already reached 139; a hundred-and-first loaner numbered 1000
 * silently ceasing to be one is a worse failure than a two-digit name being
 * accepted.
 *
 * CASE-INSENSITIVE, which deliberately DIVERGES from
 * `isAutogeneratedDeviceName` in import.ts. That one is case-sensitive because
 * being too eager there wrongly REFUSES a real rename — it errs toward doing
 * nothing. This is a convention a person types by hand into Intune or the edit
 * form, so `nghinb-loan-140` is the same intent as the uppercase spelling, and
 * refusing it would leave a loaner unflagged for a reason nobody could see.
 */
const LOANER_NAME = /^NGHINB-LOAN-\d+$/i;

export function isLoanerName(name: string | null | undefined): boolean {
  return typeof name === "string" && LOANER_NAME.test(name.trim());
}

/**
 * What a rename does to the flag.
 *
 * Returns a PARTIAL — `{}` means "leave `isLoaner` exactly as it is" — so the
 * three cases stay distinguishable at every call site:
 *
 *   into the convention   -> `{ isLoaner: true }`
 *   out of the convention -> `{ isLoaner: false }`
 *   neither name matches  -> `{}`
 *
 * THAT LAST CASE IS THE LOAD-BEARING ONE. It is what preserves a flag set by
 * hand on a device that does not follow the naming convention: the admin toggle
 * still works, and an unrelated rename must not silently switch it off. Only a
 * name moving INTO or OUT OF the convention is evidence about loaner status;
 * `NGHINB-PMACN128` becoming `NGHINB-PMACN129` is evidence about nothing.
 *
 * Takes the previous name so the transition is explicit rather than inferred
 * from the flag's current value — reading the flag would make this idempotent
 * in the wrong direction, re-asserting `false` over a hand-set `true` every
 * time any field on a non-matching device was edited.
 */
export function loanerUpdateForRename(
  previousName: string | null | undefined,
  nextName: string | null | undefined,
): { isLoaner?: boolean } {
  if (isLoanerName(nextName)) return { isLoaner: true };
  if (isLoanerName(previousName)) return { isLoaner: false };
  return {};
}
