import { isAutogeneratedDeviceName } from "./import";

/**
 * PURE derivation of a device's naming history from its ItemEdit rows.
 *
 * No Prisma import, so it unit-tests without a database — same reason
 * `readiness.ts` and `recipient-search.ts` are split out.
 *
 * The item page shows a device's CURRENT name, and a column overwritten in
 * place remembers nothing, so both questions someone actually asks about a
 * badly-named device are answerable only from history:
 *
 *   1. "This device is called BE-7J5AKRNFLP6B — what was it before?"
 *      i.e. what to rename it back to in Intune.
 *   2. "This device is flagged — what has MDM wanted to call it?"
 *      i.e. whether the proposal is new or has been pending for weeks.
 */

/** One ItemEdit row, narrowed to what this needs. `changes` is jsonb. */
export type NameEdit = {
  createdAt: Date;
  changes: unknown;
};

export type NameHistory = {
  /** The last REAL name this device carried before an autogenerated one
   *  replaced it, or null. Only meaningful when the current name is
   *  autogenerated — the caller decides whether to show it. */
  previousRealName: string | null;
  /** Autogenerated names MDM has proposed and had refused, newest first, with
   *  the current proposal excluded — a list of SUPERSEDED ones. Empty until MDM
   *  re-enrols the same device a second time. */
  supersededProposals: string[];
};

type Change = { field?: unknown; from?: unknown; to?: unknown };

function changesOf(edit: NameEdit): Change[] {
  return Array.isArray(edit.changes) ? (edit.changes as Change[]) : [];
}

const str = (v: unknown): string | null => (typeof v === "string" && v.trim() !== "" ? v : null);

/**
 * @param edits ItemEdit rows for ONE item, NEWEST FIRST.
 * @param currentProposal the item's live `mdmProposedName`, excluded from the
 *   superseded list so the disclosure never repeats what the card already says.
 */
export function deriveNameHistory(edits: NameEdit[], currentProposal: string | null): NameHistory {
  let previousRealName: string | null = null;
  const superseded: string[] = [];

  for (const edit of edits) {
    for (const c of changesOf(edit)) {
      if (c.field === "deviceName") {
        // The FIRST such change encountered walking backwards is the most
        // recent one, which is the name it lost. `from` must be a real name:
        // one autogenerated name replacing another says nothing useful about
        // what the device should be called.
        const from = str(c.from);
        if (previousRealName === null && from && !isAutogeneratedDeviceName(from)) {
          previousRealName = from;
        }
      }
      if (c.field === "mdmProposedName") {
        // `from` — the proposal being replaced. `to` is either the current
        // proposal (already on the card) or null (the flag being cleared).
        const from = str(c.from);
        if (from && from !== currentProposal && !superseded.includes(from)) {
          superseded.push(from);
        }
      }
    }
  }

  return { previousRealName, supersededProposals: superseded };
}
