import { describe, it, expect } from "vitest";
import { deriveNameHistory, type NameEdit } from "./name-history";

const AUTO_1 = "BE-7J5AKRNFLP6B";
const AUTO_2 = "BE-ZZ99YY88XX77";
const REAL = "NGHINBPMACN128";

const edit = (changes: unknown, at = "2026-08-11T00:00:00Z"): NameEdit => ({
  createdAt: new Date(at),
  changes,
});

describe("deriveNameHistory", () => {
  it("returns nothing for a device with no history", () => {
    expect(deriveNameHistory([], null)).toEqual({ previousRealName: null, supersededProposals: [] });
  });

  // Question 1: "this device is called BE-… — what do I rename it back to?"
  it("finds the real name an autogenerated one replaced", () => {
    const h = deriveNameHistory(
      [edit([{ field: "deviceName", from: REAL, to: AUTO_1 }])],
      null,
    );
    expect(h.previousRealName).toBe(REAL);
  });

  it("takes the MOST RECENT real name when there are several renames", () => {
    // Newest first, as the caller must supply them.
    const h = deriveNameHistory(
      [
        edit([{ field: "deviceName", from: "NGHINB-LATER", to: AUTO_1 }], "2026-08-10T00:00:00Z"),
        edit([{ field: "deviceName", from: "NGHINB-EARLIER", to: "NGHINB-LATER" }], "2026-01-01T00:00:00Z"),
      ],
      null,
    );
    expect(h.previousRealName).toBe("NGHINB-LATER");
  });

  // One autogenerated name replacing another says nothing about what the device
  // should be called, so it must not be offered as "the previous name".
  it("ignores an autogenerated name as a previous name", () => {
    const h = deriveNameHistory(
      [edit([{ field: "deviceName", from: AUTO_2, to: AUTO_1 }])],
      null,
    );
    expect(h.previousRealName).toBeNull();
  });

  it("skips past an autogenerated rename to the real name behind it", () => {
    const h = deriveNameHistory(
      [
        edit([{ field: "deviceName", from: AUTO_2, to: AUTO_1 }], "2026-08-10T00:00:00Z"),
        edit([{ field: "deviceName", from: REAL, to: AUTO_2 }], "2026-05-01T00:00:00Z"),
      ],
      null,
    );
    expect(h.previousRealName).toBe(REAL);
  });

  // Question 2: "how long has MDM been asking for this?"
  it("lists proposals that have been superseded", () => {
    const h = deriveNameHistory(
      [edit([{ field: "mdmProposedName", from: AUTO_1, to: AUTO_2 }])],
      AUTO_2,
    );
    expect(h.supersededProposals).toEqual([AUTO_1]);
  });

  it("excludes the CURRENT proposal, which the card already shows", () => {
    const h = deriveNameHistory(
      [edit([{ field: "mdmProposedName", from: null, to: AUTO_1 }])],
      AUTO_1,
    );
    expect(h.supersededProposals).toEqual([]);
  });

  it("does not repeat a proposal that was raised, cleared and raised again", () => {
    const h = deriveNameHistory(
      [
        edit([{ field: "mdmProposedName", from: AUTO_1, to: AUTO_2 }], "2026-08-10T00:00:00Z"),
        edit([{ field: "mdmProposedName", from: AUTO_1, to: null }], "2026-07-01T00:00:00Z"),
      ],
      AUTO_2,
    );
    expect(h.supersededProposals).toEqual([AUTO_1]);
  });

  it("reads both kinds out of a single edit row", () => {
    const h = deriveNameHistory(
      [edit([
        { field: "deviceName", from: REAL, to: AUTO_1 },
        { field: "mdmProposedName", from: AUTO_2, to: null },
      ])],
      null,
    );
    expect(h.previousRealName).toBe(REAL);
    expect(h.supersededProposals).toEqual([AUTO_2]);
  });

  it("ignores unrelated fields entirely", () => {
    const h = deriveNameHistory(
      [edit([{ field: "homeUnit", from: "A", to: "B" }, { field: "currentUserEmail", from: null, to: "x@y.mil" }])],
      null,
    );
    expect(h).toEqual({ previousRealName: null, supersededProposals: [] });
  });

  // ItemEdit.changes is jsonb — a malformed or legacy row must not take the
  // item page down.
  it("survives a changes payload that is not an array of changes", () => {
    expect(() => deriveNameHistory([edit(null), edit("nonsense"), edit({}), edit([42])], null)).not.toThrow();
    expect(deriveNameHistory([edit(null)], null).previousRealName).toBeNull();
  });

  it("ignores a blank or whitespace-only previous name", () => {
    const h = deriveNameHistory([edit([{ field: "deviceName", from: "   ", to: AUTO_1 }])], null);
    expect(h.previousRealName).toBeNull();
  });
});
